# Description: LM-Bridge (internal-only) using prebuilt image

services:
  lmbridge-init:
    profiles: ["mbms"]
    image: ${LMBRIDGE_IMAGE:-espressomatic/lm-bridge:latest}
    entrypoint: ["/bin/bash", "/metadata/init/init-mbdb.sh"]
    environment:
      MB_DB_HOST: ${MB_DB_HOST:-db}
      MB_DB_PORT: ${MB_DB_PORT:-5432}
      MB_DB_USER: ${MB_DB_USER:-musicbrainz}
      MB_DB_PASSWORD: ${MB_DB_PASSWORD:-musicbrainz}
      MB_DB_NAME: ${MB_DB_NAME:-musicbrainz_db}
      LMBRIDGE_CACHE_DB: ${LMBRIDGE_CACHE_DB:-lm_cache_db}
      LMBRIDGE_CACHE_USER: ${LMBRIDGE_CACHE_USER:-lidarr}
      LMBRIDGE_CACHE_PASSWORD: ${LMBRIDGE_CACHE_PASSWORD:-lidarr}
    restart: "no"
    depends_on:
      db:
        condition: service_started
      bootstrap:
        condition: service_completed_successfully

  lmbridge:
    profiles: ["mbms"]
    image: ${LMBRIDGE_IMAGE:-espressomatic/lm-bridge:latest}
    ports:
      - "${LMBRIDGE_PORT:-5001}:5001"
    environment:
      # --- General ---
      DEBUG: "${DEBUG:-false}"
      PRODUCTION: "${PRODUCTION:-false}"
      LIDARR_METADATA_CONFIG: "${LIDARR_METADATA_CONFIG:-BRIDGE}"
      USE_CACHE: "${USE_CACHE:-true}"
      ENABLE_STATS: "${ENABLE_STATS:-false}"
      ROOT_PATH: "${ROOT_PATH:-}"

      # --- Redis ---
      REDIS_HOST: "${REDIS_HOST:-redis}"
      REDIS_PORT: "${REDIS_PORT:-6379}"

      # --- Solr mirror ---
      PROVIDERS__SOLRSEARCHPROVIDER__1__SEARCH_SERVER: "${SOLR_URL:-http://search:8983/solr}"

      # --- MusicBrainz DB creds (set these to match your mirror) ---
      PROVIDERS__MUSICBRAINZDBPROVIDER__1__DB_HOST: "${MB_DB_HOST:-db}"
      PROVIDERS__MUSICBRAINZDBPROVIDER__1__DB_PORT: "${MB_DB_PORT:-5432}"
      PROVIDERS__MUSICBRAINZDBPROVIDER__1__DB_USER: "${MB_DB_USER:-musicbrainz}"
      PROVIDERS__MUSICBRAINZDBPROVIDER__1__DB_PASSWORD: "${MB_DB_PASSWORD:-musicbrainz}"

      # --- Postgres cache (lm_cache_db) ---
      POSTGRES_CACHE_HOST: "${LMBRIDGE_CACHE_HOST:-db}"
      POSTGRES_CACHE_PORT: "${LMBRIDGE_CACHE_PORT:-5432}"

      # --- External providers (fill in later) ---
      FANART_KEY: "${FANART_KEY:-}"
      TADB_KEY: "${TADB_KEY:-2}"
      LASTFM_KEY: "${LASTFM_KEY:-}"
      LASTFM_SECRET: "${LASTFM_SECRET:-}"
      SPOTIFY_ID: "${SPOTIFY_ID:-}"
      SPOTIFY_SECRET: "${SPOTIFY_SECRET:-}"
      SPOTIFY_REDIRECT_URL: "${SPOTIFY_REDIRECT_URL:-http://HOST_IP:5001}"
    restart: unless-stopped
    depends_on:
      lmbridge-init:
        condition: service_completed_successfully
      db:
        condition: service_started
      search:
        condition: service_started
      redis:
        condition: service_started
